markdown: kramdown
environment: production
baseurl: /blog
permalink: pretty
highlighter: rouge
theme: jekyll-theme-architect

title: The title of your site
description: short description of your site's purpose

show_downloads: true
google_analytics:


collections:
  downloads:
    output: true
    permalink: /downloads/:path/
