markdown: kramdown
environment: production
permalink: pretty
highlighter: rouge
title: The title of your site
description: short description of your site's purpose
baseurl:

show_downloads: true
google_analytics: UA-2498474-2


collections:
  downloads:
    output: true
    permalink: /downloads/:path/
