markdown: kramdown
environment: production
baseurl: /blog
permalink: pretty
highlighter: pygments


collections:
  downloads:
    output: true
    permalink: /downloads/:path/

theme: jekyll-theme-dinky
