markdown: kramdown
environment: production
baseurl: /blog
permalink: pretty

collections:
  downloads:
    output: true
    permalink: /downloads/:path/

theme: jekyll-theme-cayman

 
# Conversion
highlighter: rouge
lsi:         false
excerpt_separator: "\n"
incremental: false


# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname
show_dir_listing: false


# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
