markdown: kramdown
environment: production
permalink: pretty
highlighter: rouge
title: The title of your site
description: short description of your site's purpose
baseurl: 

show_downloads: true
google_analytics:


collections:
  downloads:
    output: true
    permalink: /downloads/:path/
